Add methods and data
SamTush/blog-app pull request #2
Opened 2023-06-15 16:48 UTC by SamTush

## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Add methods
- [x] Add data to database

## Description of the task to be completed ↓↓ 

- Create blog app

#### Thanks for reviewing my PR 😊

2023-06-15 17:25 UTC, OyePriscilla requested changes
Hi @SamTush ✔️ , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Set up associations between models ✔️
Implemented methods for all the models as expected ✔️

## Required Changes ♻️

- [ ] Please kindly fix the broken link in the tech stack section of your README file, I guess there is a typo error; `rubyonrails.org` not `rubyrails.org`. ℹ️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 17:25 UTC, OyePriscilla commented on app/models/user.rb
> +  has_many :comments
- [ ] Please kindly add the `likes` association to this model in accordance to the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png)

2023-06-15 17:25 UTC, OyePriscilla commented on app/models/post.rb
> +  has_many :comments
- [ ] Please kindly add the likes association to this model in accordance to the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png)

2023-06-16 09:55 UTC, SamTush commented
Thank you @OyePriscilla for reviewing my PR😎

2023-06-16 10:16 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @SamTush  

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request✔️
- Associations well setup✔️
- methods well added ✔️ 
- No linter errors✔️

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 ✔️✔️

![t](https://media.giphy.com/media/d0NnEG1WnnXqg/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 11:10 UTC, SamTush commented
thank you @tufoinnkuo10 for reviewing my PR😎

2023-06-16 11:10 UTC, merged